---
# ansible/roles/base/tasks/main.yml
- name: Generate locales
  ansible.builtin.import_tasks: generate_locales.yml

- name: Set timezone
  community.general.timezone:
    name: "{{ server_timezone }}"

- name: Enable time synchronization
  ansible.builtin.systemd_service:
    name: systemd-timesyncd.service
    state: started
    enabled: true

- name: Install apt updates
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
