---
- name: Remove simone from sudoers
  community.general.file_remove:
    path: /etc/sudoers.d
    pattern: simone

- name: Remove simone directory
  ansible.builtin.file:
    dest: /home/simone
    state: absent

- name: Get rid of simone
  ansible.builtin.user:
    name: simone
    state: absent
