---
- name: Create simone User
  ansible.builtin.user:
    name: simone
    groups: root

- name: Add SSH for simone
  ansible.posix.authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINeTrf/WlxsACkBn1ZU4eI4gt/h0siLzG8c/UlMgo3a2 ansible-kubaxius@Deimos"

- name: Add sudoers for simone
  ansible.builtin.copy:
    src: sudoer_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root
    mode: "0440"
