[project]
name = "pantheon-systems-cli"
version = "0.1.0"
description = "Easily rebuildable, scalable personal solution for creating and managing servers."
readme = "README.md"
authors = [
    { name = "Jakub Niedźwiedź", email = "jakub.niedzwiedz@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "typer>=0.27.1",
]

[tool.uv.build-backend]
module-root = ""

[project.scripts]
pantheon = "pantheon_systems_cli:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.basedpyright]
typeCheckingMode = "strict"