---
- name: Install Apt Updates
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  changed_when: false
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Print System Name
  ansible.builtin.debug:
    msg: "This is {{ ansible_facts['distribution'] }}!"
