---
# roles/base/defaults/main.yml

base_journald_limits:
  storage: persistent
  system_max_use: 500M
  system_keep_free: 2G
  max_retention: 30day

base_packages:
  - ca-certificates
  - logrotate
  - unattended-upgrades

base_units:
  - logrotate.timer

base_automatic_security_updates: true
base_automatic_reboot: false
