---
# ansible/roles/nginx/tasks/main.yml
- name: Install Nginx
  ansible.builtin.apt:
    package: nginx
    update_cache: true
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Enable and run Nginx
  ansible.builtin.systemd_service:
    service: nginx
    state: started
    enabled: true
