---
- name: Test play
  hosts: all
  become: true
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: "This is {{ ansible_facts['distribution'] }}!"
      when: ansible_facts["distribution"] in ["Ubuntu", "Debian"]

    - name: Install apache and php packages
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        update_cache: true
        state: present
      when: ansible_facts["distribution"] == "Ubuntu"
