---
- name: Setup Play
  hosts: all
  become: true
  tags: always
  pre_tasks:
    - name: Install Apt Updates
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Print System Name
      ansible.builtin.debug:
        msg: "This is {{ ansible_facts['distribution'] }}!"

- name: Set Up Simone
  hosts: all
  become: true
  tags: simone_setup
  tasks:
    - name: Create simone User
      ansible.builtin.user:
        name: simone
        groups: root

    - name: Add SSH for simone
      ansible.posix.authorized_key:
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINeTrf/WlxsACkBn1ZU4eI4gt/h0siLzG8c/UlMgo3a2 ansible-kubaxius@Deimos"

    - name: Add sudoers for simone
      ansible.builtin.copy:
        src: sudoer_simone
        dest: /etc/sudoers.d/simone
        owner: root
        group: root
        mode: "0440"

- name: Remove Simone
  hosts: all
  become: true
  tags: simone_removal
  tasks:
    - name: Remove simone from sudoers
      community.general.file_remove:
        path: /etc/sudoers.d
        pattern: simone

    - name: Remove simone directory
      ansible.builtin.file:
        dest: /home/simone
        state: absent

    - name: Get rid of simone
      ansible.builtin.user:
        name: simone
        state: absent

- name: Set Up Web Server
  hosts: web_servers
  become: true
  tasks:
    - name: Install Apache and PHP Packages
      tags: apache, web
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        update_cache: true
        state: present
      when: ansible_facts["distribution"] == "Ubuntu"

- name: Set Up DB Server
  hosts: db_servers
  become: true
  tasks:
    - name: Install MariaDB
      tags: mariadb, web
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: true
      when: ansible_facts["distribution"] == "Ubuntu"

- name: Set Up File Server
  hosts: file_servers
  tags: files
  become: true
  tasks:
    - name: Install Samba
      tags: samba
      ansible.builtin.apt:
        package: samba
        state: present
        update_cache: true
      when: ansible_facts["distribution"] == "Ubuntu"
