---
- name: Install Apache and PHP Packages
  tags: apache, web
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
    update_cache: true
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"
